"""empty message

Revision ID: 162663896c9b
Revises: 
Create Date: 2021-10-30 23:10:00.781972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162663896c9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('writer', sa.String(length=20), nullable=False),
    sa.Column('w_date', sa.DateTime(), nullable=False),
    sa.Column('itsBroNm', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('nation_wide',
    sa.Column('rk', sa.Integer(), nullable=False),
    sa.Column('itsBroNm', sa.String(length=20), nullable=True),
    sa.Column('areaNm', sa.String(length=20), nullable=True),
    sa.Column('areaCode', sa.String(length=20), nullable=False),
    sa.Column('baseYm', sa.String(length=20), nullable=False),
    sa.Column('imgLink', sa.String(length=100), nullable=False),
    sa.Column('dtlAddrNm', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('rk')
    )
    op.create_table('region',
    sa.Column('rk', sa.Integer(), nullable=False),
    sa.Column('itsBroNm', sa.String(length=20), nullable=True),
    sa.Column('areaNm', sa.String(length=20), nullable=True),
    sa.Column('areaCode', sa.String(length=20), nullable=False),
    sa.Column('baseYm', sa.String(length=20), nullable=False),
    sa.Column('imgLink', sa.String(length=500), nullable=True),
    sa.Column('dtlAddrNm', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('rk')
    )
    op.drop_table('review')
    op.drop_table('sqlite_sequence')
    op.alter_column('review_nlp', 'gu_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('review_nlp', 'place_name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_nlp', 'place_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('review_nlp', 'gu_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.create_table('review',
    sa.Column('gu_name', sa.TEXT(), nullable=False),
    sa.Column('place_name', sa.TEXT(), nullable=False),
    sa.Column('score', sa.TEXT(), nullable=False),
    sa.Column('img_link', sa.TEXT(), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('review_score', sa.TEXT(), nullable=False),
    sa.Column('review', sa.TEXT(), nullable=False)
    )
    op.drop_table('region')
    op.drop_table('nation_wide')
    op.drop_table('board')
    # ### end Alembic commands ###
